version: 2
jobs:
  test:
    working_directory: ~/project/src
    docker:
      - image: circleci/php:8-node-browsers

      - image: circleci/mysql:8.0.25
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_USER: laravel
          MYSQL_DATABASE: laravel
          MYSQL_ROOT_PASSWORD: root
          MYSQL_PASSWORD: root

    steps:
      - checkout:
          path: ~/project

      - run: sudo apt update
      - run: sudo docker-php-ext-install zip pdo pdo_mysql bcmath

      - run: mv .env.example .env

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run: php artisan key:generate
      - run: php artisan migrate --env=testing --force
      - run: php artisan db:seed

      - run: ./vendor/bin/phpunit

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - test
